# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetDetail',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(max_length=88, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('game_id', models.IntegerField(blank=True, null=True)),
                ('minimumbet', models.CharField(max_length=30)),
                ('spread', models.CharField(max_length=30)),
                ('left_odds', models.IntegerField(blank=True, null=True)),
                ('middle_odds', models.IntegerField(blank=True, null=True)),
                ('right_odds', models.IntegerField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('time_stamp', models.CharField(max_length=30)),
                ('confirmations', models.IntegerField(blank=True, null=True)),
                ('network_id', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
