# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('address_from', models.CharField(max_length=42)),
                ('address_to', models.CharField(max_length=42)),
                ('amount', models.CharField(max_length=30)),
                ('bet_block_hash', models.CharField(max_length=66)),
                ('bet_mask', models.CharField(max_length=4)),
                ('commit', models.CharField(max_length=66)),
                ('dice_payment', models.CharField(max_length=30)),
                ('jackpot_payment', models.CharField(max_length=30)),
                ('modulo', models.CharField(max_length=4)),
                ('reveal', models.CharField(max_length=66)),
                ('reveal_block_hash', models.CharField(max_length=66)),
                ('reveal_tx_hash', models.CharField(max_length=66)),
                ('tx_hash', models.CharField(max_length=66)),
                ('main_contract_txhash', models.CharField(default='', max_length=88)),
                ('network_id', models.IntegerField(default=1)),
                ('time_stamp', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.DateTimeField(db_index=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
