# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('network_id', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=42)),
                ('random_number', models.CharField(max_length=42)),
                ('messageHash', models.CharField(max_length=66)),
                ('s', models.CharField(max_length=100)),
                ('r', models.CharField(max_length=100)),
                ('v', models.CharField(max_length=3)),
                ('signature', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
