# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-10 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0004_dicerecord_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicerecord',
            name='amount',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dicerecord',
            name='jackpot_payment',
            field=models.IntegerField(max_length=30),
        ),
    ]
