# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-10 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0005_auto_20181010_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicerecord',
            name='amount',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dicerecord',
            name='jackpot_payment',
            field=models.CharField(max_length=30),
        ),
    ]
