# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0007_auto_20181010_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Random',
        ),
    ]
