# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0008_delete_random'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicerecord',
            old_name='main_contract_txhash',
            new_name='contract_address',
        ),
    ]
