# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betrecord',
            old_name='time_str',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='betrecord',
            name='contract',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='betrecord',
            name='quantity',
            field=models.CharField(max_length=30),
        ),
    ]
