# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_record', '0002_auto_20180621_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='betrecord',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
