# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_record', '0004_auto_20180625_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betrecord',
            name='network_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='betrecord',
            name='time',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
