# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_record', '0005_auto_20180626_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='betrecord',
            name='main_contract_txhash',
            field=models.CharField(default='', max_length=88),
        ),
    ]
