# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_record', '0006_betrecord_main_contract_txhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='betrecord',
            name='choice',
            field=models.CharField(default='', max_length=3),
        ),
    ]
