# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betitem',
            name='deposit',
            field=models.FloatField(),
        ),
    ]
